

################################# Analysis ####################################################################################################################################################################################


analysis-git-submodules:
  extends: .tags-linux
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: never
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_git:v2.25.1
  stage: analysis
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - source ./ci/tools/git-branch.sh
    - ./ci/analysis-git-submodule.sh


################################# Deploy ####################################################################################################################################################################################

#### Deploy Gitlab.com

.tag-deploy:
  tags:
    - x86_64
    - linux
    - docker
    - no_proxy




.deploy-gitlab-com:
  extends: .tag-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: never
  stage: deploy
  allow_failure: true

deploy-sonarqube-linux:
  extends: .deploy-gitlab-com
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_sonarqube:v3.0.3
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  dependencies:
    - analysis-cppcheck
    - coverage-linux
    - analysis-clang
  script:
    - export REPORTS_DIR="clang_reports"
    - source ./ci/tools/git-tag.sh
    - source ./ci/tools/git-branch.sh
    - ./ci/deploy/deploy-sonarqube-linux.sh

deploy-builds-linux-windows:
  extends: .deploy-gitlab-com
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_git:v2.25.1
  dependencies:
    - build-linux-gcc
    - build-windows-gcc
    # - build-macos-clang-x64-sse4.2
  artifacts:
     name: builds
     when: always
     paths:
      - builds/
  before_script:
    ## https://docs.gitlab.com/ee/ci/ssh_keys/
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git config --global user.email "adrien.cassagne@inria.fr"
    - git config --global user.name "Adrien Cassagne"
  script:
    - source ./ci/tools/git-branch.sh
    - source ./ci/tools/git-tag.sh
    - source ./ci/tools/git-hash.sh
    - source ./ci/tools/git-date.sh
    - source ./ci/tools/git-message.sh
    - source ./ci/tools/git-author.sh
    - source ./ci/tools/git-version.sh
    # - ./ci/deploy-builds-linux.sh build_linux_gcc_x64_sse4.2 build_linux_gcc_x64_avx2 build_windows_gcc_x86_sse4.2 build_windows_gcc_x64_avx2 build_macos_clang_x64_sse4.2
    - ./ci/deploy/deploy-builds-linux.sh build_linux_gcc_x64_sse4.2 build_linux_gcc_x64_avx2 build_windows_gcc_x86_sse4.2 build_windows_gcc_x64_avx2

deploy-upload-ppa:
  extends: .tag-deploy
  rules:
  - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "ppa_upload"
    when: always
  - if: $CI_PIPELINE_SOURCE == "schedule"
    when: never
  - when: never
  image: registry.gitlab.com/aff3ct/aff3ct/x86_64_ubuntu_ppa
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  dependencies:
    - analysis-documentation
  allow_failure: true
  artifacts:
    name: ppa_files
    when: always
    paths:
      - build/Debian/xenial/*.xz
      - build/Debian/xenial/*.dsc
      - build/Debian/xenial/*.build
  before_script:
    - echo "$GPG_PRIVATE_KEY" | gpg --batch --import --pinentry-mode loopback --no-tty
  script:
    - source ./ci/tools/git-branch.sh
    - source ./ci/tools/threads.sh
    - ./ci/deploy/deploy-upload-ppa.sh
