#- if : $CI_SERVER_HOST == "github.com" && $CI_COMMIT_BRANCH == "develop" &&  $CI_PIPELINE_SOURCE != "schedule"

################################# Deploy ####################################################################################################################################################################################

.deploy-github-com:
  tags:
    - linux
  dependencies:
    - coverage-linux
  stage: deploy
  allow_failure: true


pages:
  extends: .deploy-github-com
  script:
    - mv code_coverage_report/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days